application: realestatecalculator-1256
version: test-001
runtime: python27
api_version: 1
threadsafe: true

handlers:

#To look the browser tab logo
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /app
  static_dir: app

- url: /components
  static_dir: components

- url: /tools
  static_dir: tools

- url: /rentalCalculator
  static_dir: rentalCalculator

- url: /controllers
  static_dir: controllers

- url: /directives
  static_dir: directives

- url: /img 
  static_dir: img

- url: /assets 
  static_dir: assets

- url: /lib 
  static_dir: lib

- url: /services 
  static_dir: services

- url: /css
  static_dir: css

- url: /angular
  static_dir: angular

- url: /scripts 
  static_dir: scripts

- url: /bootstrap 
  static_dir: bootstrap

- url: /jquery
  static_dir: jquery

- url: /views
  static_dir: views

- url: /templates
  static_dir: templates

  # [ the .app was added to specify that we are using a WSGI application
  #   which is needed to enable threadsafe actions]

- url: /.*
  script: main.application 

# [Libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

